spring:
  cloud:
    config:
      username: ${CONFIG_SECURITY_USERNAME}
      password: ${CONFIG_SECURITY_PASSWORD}
      uri: ${CONFIG_URI}
  config:
    import: "configserver:"
  application:
    name: web-service