spring:
  cloud:
    config:
      username: "administrator"
      password: "Bilge123!!"
      uri: "http://192.168.1.201:8888"
  config:
    import: "configserver:"
  application:
    name: auth-service
  zipkin:
    enable: true
    base-url: http://34.116.235.46:9411/
    service:
      name: auth-server