server:
  port: ${AUTH_SERVICE_PORT}

spring:
  redis:
    host: ${HOST}
    port: ${REDIS_PORT}
  rabbitmq:
    host: ${HOST}
    port: ${RABBIT_PORT}
    username: ${AUTH_SERVICE_DATASOURCE_USERNAME}
    password: ${AUTH_SERVICE_DATASOURCE_PASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${AUTH_SERVICE_DATASOURCE_URL}
    username: ${AUTH_SERVICE_DATASOURCE_USERNAME}
    password: ${AUTH_SERVICE_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_BASEURL}
    service-name: auth-service

myapplication:
  userservice: ${AUTH_SERVICE_MYAPPLICATION_USERSERVICE}

logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: authservice.log