server:
  port: 8888

spring:
  security:
    user:
      name: administrator
      password: Bilge123!!
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
  zipkin:
    enable: true
    base-url: http://34.116.235.46:9411/
    service:
      name: config-server